name: kolibri
adopt-info: kolibri-gnome
base: core22
architectures:
- amd64
confinement: strict
grade: stable
compression: lzo
icon: icon.png
passthrough:
  license: MIT
contact: https://github.com/kenvandine/kolibri-snap/issues
issues: https://github.com/kenvandine/kolibri-snap/issues
website: https://learningequality.org/kolibri/

layout:
  /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0:
    symlink: $SNAP/gnome-platform/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0
  /usr/share/kolibri-app:
    bind: $SNAP/usr/share/kolibri-app

environment:
  PYTHONPATH: $SNAP/lib/python3.10/site-packages:$SNAP/usr/local/lib/python3.10/dist-packages:$SNAP/gnome-platform/usr/lib/python3/dist-packages:$SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
  KOLIBRI_HOME: $SNAP_USER_COMMON/.kolibri
  GST_PLUGIN_PATH: $SNAP/usr/lib/x86_64-linux-gnu/gstreamer-1.0
  GST_PLUGIN_SYSTEM_PATH: $SNAP/usr/x86_64-linux-gnu/lib/gstreamer-1.0
  GST_PLUGIN_SCANNER: $SNAP/usr/lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner

plugs:
  shmem:
    interface: shared-memory
    private: true

apps:
  kolibri:
    extensions: [gnome]
    daemon: simple
    passthrough: #///! TODO: Remove once daemon-scope lands in snapcraft
      daemon-scope: user
    restart-condition: always
    command: kolibri.sh
    plugs:
      - network
      - audio-playback
      - network-status
      - mount-observe
      - shmem

  kolibri-gnome:
    command: usr/bin/kolibri-gnome
    common-id: org.learningequality.Kolibri
    desktop: usr/share/applications/org.learningequality.Kolibri.desktop
    extensions: [gnome]
    plugs:
      - network
      - audio-playback
      - network-status
      - mount-observe

parts:
  launcher:
    plugin: dump
    source: launcher
    override-build: |
      cp kolibri.sh $CRAFT_PART_INSTALL/

  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/
    build-packages:
      - on amd64:
        - gcc-multilib
        - g++-multilib

  kolibri-desktop-auth-plugin:
    after: [ kolibri ]
    source: https://github.com/endlessm/kolibri-desktop-auth-plugin.git
    plugin: python
    python-requirements: [ 'requirements.txt' ]
    stage:
      - lib/python3.10/site-packages/kolibri_desktop_auth_plugin*
      - -bin/activate*
      - -bin/__pycache__
    prime:
      - lib/python3.10/site-packages/kolibri_desktop_auth_plugin*
      - -bin/activate*

  kolibri-explore-plugin:
    after: [ kolibri ]
    source: https://github.com/endlessm/kolibri-explore-plugin.git
    plugin: python
    python-requirements: [ 'requirements.txt' ]
    stage:
      - lib/python3.10/site-packages/kolibri_explore_plugin*
      - -bin/activate*
      - -bin/__pycache__
    prime:
      - lib/python3.10/site-packages/kolibri_explore_plugin
      - -bin/activate*

  kolibri-gnome:
    after: [ kolibri ]
    source: https://github.com/learningequality/kolibri-installer-gnome.git
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
    parse-info: [usr/share/metainfo/org.learningequality.Kolibri.metainfo.xml]
    stage-packages:
      - python3-setproctitle
    organize:
      usr/local/lib/python3.10/dist-packages/kolibri_gnome: lib/python3.10/site-packages/kolibri_gnome
      usr/local/lib/python3.10/dist-packages/kolibri_gnome_launcher: lib/python3.10/site-packages/kolibri_gnome_launcher
      usr/local/lib/python3.10/dist-packages/kolibri_daemon: lib/python3.10/site-packages/kolibri_daemon
      usr/local/lib/python3.10/dist-packages/kolibri_app: lib/python3.10/site-packages/kolibri_app

  kolibri:
    plugin: python
    source: https://github.com/learningequality/kolibri.git
    python-requirements: [ 'requirements.txt' ]
    organize:
      lib/python3.10/site-packages/magicbus: lib/python3.10/site-packages/kolibri/dist/magicbus
    stage:
      - -bin/activate*
    prime:
      - lib/python3.10/site-packages/*
      - usr/share/kolibri*
      - -usr/lib/python3/dist-packages/kolibri/dist/cext/cp*
      - -bin/activate*

  libraries:
    plugin: nil
    stage-packages:
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-good
      - libgstreamer1.0-0
