name: kolibri
adopt-info: kolibri-gnome
base: core22
architectures:
- amd64
confinement: strict
grade: stable
compression: lzo
icon: icon.png
passthrough:
  license: MIT
contact: https://github.com/kenvandine/kolibri-snap/issues
issues: https://github.com/kenvandine/kolibri-snap/issues
website: https://learningequality.org/kolibri/

layout:
  /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0:
    symlink: $SNAP/gnome-platform/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0
  /usr/share/kolibri-app:
    bind: $SNAP/usr/share/kolibri-app

environment:
  PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/lib/python3.10/site-packages:$SNAP/gnome-platform/usr/lib/python3/dist-packages:$PYTHONPATH
  GST_PLUGIN_PATH: $SNAP/usr/lib/x86_64-linux-gnu/gstreamer-1.0
  GST_PLUGIN_SYSTEM_PATH: $SNAP/usr/x86_64-linux-gnu/lib/gstreamer-1.0
  GST_PLUGIN_SCANNER: $SNAP/usr/lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner
  KOLIBRI_DEBUG: 1
  KOLIBRI_HOME: $SNAP_USER_COMMON/.kolibri
  KOLIBRI_COMMAND: kolibri
  DJANGO_SETTINGS_MODULE: kolibri.deployment.default.settings.base

plugs:
  shmem:
    interface: shared-memory
    private: true

apps:
  kolibri:
    extensions: [gnome]
    daemon: simple
    passthrough: #///! TODO: Remove once daemon-scope lands in snapcraft
      daemon-scope: user
    restart-condition: always
    command: kolibri.sh
    plugs:
      - network
      - audio-playback
      - network-status
      - mount-observe
      - shmem

  kolibri-gnome:
    command: usr/bin/kolibri-gnome
    common-id: org.learningequality.Kolibri
    desktop: usr/share/applications/org.learningequality.Kolibri.desktop
    extensions: [gnome]
    plugs:
      - network
      - audio-playback
      - network-status
      - mount-observe

parts:
  launcher:
    plugin: dump
    source: launcher
    override-build: |
      cp kolibri.sh $CRAFT_PART_INSTALL/

  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/
    build-packages:
      - on amd64:
        - gcc-multilib
        - g++-multilib

  kolibri-desktop-auth-plugin:
    after: [ kolibri ]
    source: https://github.com/endlessm/kolibri-desktop-auth-plugin.git
    plugin: python
    python-requirements: [ 'requirements.txt' ]
    build-environment:
      - KOLIBRI_MODULE_PATH: usr/lib/python3/dist-packages/kolibri
    override-build: |
      python3 setup.py install --force --prefix=/usr --root=$CRAFT_PART_INSTALL --no-compile -O0 --install-layout=deb
    stage:
      - usr/lib/python3/dist-packages/kolibri_desktop_auth_plugin*
      - -bin/activate*
      - -bin/__pycache__
    prime:
      - usr/lib/python3/dist-packages/kolibri_desktop_auth_plugin*
      - -bin/activate*

  kolibri-explore-plugin:
    after: [ kolibri ]
    source: https://github.com/endlessm/kolibri-explore-plugin.git
    plugin: python
    python-requirements: [ 'requirements.txt' ]
    build-environment:
      - KOLIBRI_MODULE_PATH: usr/lib/python3/dist-packages/kolibri
    build-packages:
      - wget
      - unzip
    stage:
      - usr/lib/python3/dist-packages/kolibri_explore_plugin*
      - -bin/activate*
      - -bin/__pycache__
    prime:
      - usr/lib/python3/dist-packages/kolibri_explore_plugin*
      - -bin/activate*
    override-build: |
      python3 setup.py install --force --prefix=/usr --root=$CRAFT_PART_INSTALL --no-compile -O0 --install-layout=deb
    override-prime: |
      craftctl default
      mkdir -p $CRAFT_PRIME/usr/lib/python3/dist-packages/kolibri_explore_plugin
      cd $CRAFT_PRIME/usr/lib/python3/dist-packages/kolibri_explore_plugin
      wget https://github.com/endlessm/kolibri-explore-plugin/releases/download/v6.1.0/apps-bundle.zip
      rm -rf apps
      unzip apps-bundle.zip
      rm apps-bundle.zip*
      mkdir -p $CRAFT_PRIME/usr/lib/python3/dist-packages/kolibri_explore_plugin/static/collections/
      cd $CRAFT_PRIME/usr/lib/python3/dist-packages/kolibri_explore_plugin/static/collections/
      rm *00*.json* || true
      wget https://github.com/endlessm/endless-key-collections/blob/main/json/artist-0001.json
      wget https://github.com/endlessm/endless-key-collections/blob/main/json/athlete-0001.json
      wget https://github.com/endlessm/endless-key-collections/blob/main/json/curious-0001.json
      wget https://github.com/endlessm/endless-key-collections/blob/main/json/explorer-0001.json
      wget https://github.com/endlessm/endless-key-collections/blob/main/json/inventor-0001.json
      wget https://github.com/endlessm/endless-key-collections/blob/main/json/scientist-0001.json

  kolibri-gnome:
    after: [ kolibri ]
    source: https://github.com/learningequality/kolibri-installer-gnome.git
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
    parse-info: [usr/share/metainfo/org.learningequality.Kolibri.metainfo.xml]
    stage-packages:
      - python3-setproctitle
    build-environment:
     - KOLIBRI_MODULE_PATH: usr/lib/python3/dist-packages/kolibri
    #organize:
    #  usr/local/lib/python3.10/dist-packages/kolibri_gnome: lib/python3.10/site-packages/kolibri_gnome
    #  usr/local/lib/python3.10/dist-packages/kolibri_gnome_launcher: lib/python3.10/site-packages/kolibri_gnome_launcher
    #  usr/local/lib/python3.10/dist-packages/kolibri_daemon: lib/python3.10/site-packages/kolibri_daemon
    #  usr/local/lib/python3.10/dist-packages/kolibri_app: lib/python3.10/site-packages/kolibri_app

  kolibri:
    after: [ patches ]
    plugin: python
    #source: https://github.com/learningequality/kolibri/archive/refs/tags/v0.16.0-alpha17.tar.gz
    source: https://github.com/learningequality/kolibri/releases/download/v0.16.0-alpha17/kolibri-0.16.0a17.tar.gz
    #source: https://github.com/learningequality/kolibri.git
    #source-tag: v0.16.0-alpha17
    #python-requirements: [ 'requirements.txt' ]
    #build-environment:
    #  - KOLIBRI_MODULE_PATH: usr/lib/python3/dist-packages/kolibri
    prime:
      #- -lib/python3.10/site-packages/kolibri*
      - usr/share/kolibri*
      - bin/kolibri
      #- lib/systemd/system/kolibri.service
      - usr/lib/python3/dist-packages
      - usr/share/kolibri*
      - -usr/lib/python3/dist-packages/kolibri/dist/cext/cp*
    #override-pull: |
    #  craftctl default
    #  patch -p1 < $CRAFT_PART_SRC/../../patches/src/0001-Allow-superuser-to-be-null-in-device-provision-API.patch
    #  #patch -p1 < $CRAFT_PART_SRC/../../patches/src/default_plugins.patch
    #  #craftctl set version=$(git describe --tags --abbrev=10)
    #override-build: |
    #  python3 setup.py install --force --prefix=/usr --root=$CRAFT_PART_INSTALL --no-compile -O0 --install-layout=deb
    #  sed -i 's|/snap/gnome-42-2204-sdk/current||g' $CRAFT_PART_INSTALL/usr/bin/kolibri
    #  pip install --target=$CRAFT_PART_INSTALL/usr/lib/python3/dist-packages magicbus

    #override-prime: |
    #  craftctl default
    #  find $CRAFT_PRIME/lib/python3.10/site-packages/kolibri/ -type f,l -name *.pyc -exec rm -f "{}" \;

  patches:
    plugin: nil
    source: patches

  libraries:
    plugin: nil
    stage-packages:
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-good
      - libgstreamer1.0-0
    prime:
      - usr/lib/*/gstreamer-1.0
      - usr/lib/*/libgst*
